[package]
name = "mdict_tools"
version = "0.1.0"
edition = "2021"

[dependencies]
xmlparser = "0.13.6"
log = "0.4.25"
zune-inflate = "0.2.54"
paste = "1.0.15"
minilzo-rs = "0.6.1"
regex = "1.11.1"
binrw = "0.8"

[dev-dependencies]
get-size2 = "0.1.3"
sysinfo = "0.33"
